#! /bin/bash
# $IFS 内部域分隔符

output_args_one_per_line () {
    for arg do
        echo "[$arg]"
    done
}

echo; echo "IFS=\" \""
echo "--------"
IFS=" "
var=" a  b c   "
output_args_one_per_line $var


echo; echo "IFS=:"
echo "--------"
IFS=":"
var=":a::b:c:::"
output_args_one_per_line $var

echo
exit 0
